CC = gcc
FLAGS = -g
LEX = lex
YACC = yacc

mypc: y.tab.o lex.yy.o
	$(CC) $(FLAGS) -o mypc y.tab.o lex.yy.o -ll -ly

y.tab.o: y.tab.c
	$(CC) $(FLAGS) -c y.tab.c

y.tab.c: pc.y
	$(YACC) -y -dv pc.y

lex.yy.o: lex.yy.c
	$(CC) $(FLAGS) -c lex.yy.c

lex.yy.c: pc.l
	$(LEX) -l pc.l

clean:
	rm -f mypc *.o y.tab.* lex.yy.* 
